tasks:
  - init: |
      pip install --upgrade streamlit numpy pandas
    command: |
      streamlit run app.py --server.port=8501 --server.address=0.0.0.0

ports:
  - port: 8501
    onOpen: open-preview
